#cloud-config

write_files:
- path: /etc/consul.d/consul.hcl
  permissions: 0644
  owner: root
  content: |
    server = true
    datacenter = "dc1"
    bootstrap_expect = 1
    log_level = "DEBUG"
    encrypt = "x7ohWiQjK7d/OSBvnENBXsfKxNt2GXWI7G11eejUSeI="
    data_dir = "/tmp"
    advertise_addr = "172.16.1.9"
    connect {
      enabled = true
    }
    node_name = "ctrlplane"
    enable_central_service_config = true
- path: /etc/nomad.d/nomad.hcl
  permissions: 0644
  owner: root
  content: |
    data_dir = "/etc/nomad.d"
    bind_addr = "172.16.1.9"
    server {
      enabled          = true
      bootstrap_expect = 1
    }
    addresses {
      http = "127.0.0.1"
    }
    advertise {
      http  = "172.16.1.9"
      rpc  = "172.16.1.9"
      serf  = "172.16.1.9"
    }

runcmd:
- [ systemctl, daemon-reload ]
- [ systemctl, restart, consul ] 
- [ systemctl, restart, nomad ] 
