#cloud-config

write_files:
- path: /etc/consul.d/consul.hcl
  permissions: 0644
  owner: root
  content: |
    data_dir = "/tmp"
    encrypt = "x7ohWiQjK7d/OSBvnENBXsfKxNt2GXWI7G11eejUSeI="
    advertise_addr = "172.16.1.10"
    retry_join = ["172.16.1.9"]
    retry_interval = "5s"
    addresses {
        dns  = "127.0.0.1 172.17.0.1"
        http = "127.0.0.1 172.17.0.1"
        grpc = "127.0.0.1 172.17.0.1"
    }
    ports {
        grpc = 8502
    }
    node_name = "ingress"
    enable_central_service_config = true
- path: /etc/nomad.d/nomad.hcl
  permissions: 0644
  owner: root
  content: |
    data_dir  = "/etc/nomad.d"
    bind_addr = "172.16.1.10"
    client {
      enabled           = true
      network_interface = "eth1"
      meta {
        instance_group  = "ingress"
      }
    }
    addresses {
      http = "127.0.0.1"
    }
    advertise {
      http = "172.16.1.10"
      rpc  = "172.16.1.10"
      serf = "172.16.1.10"
    }

runcmd:
- [ systemctl, daemon-reload ]
- [ systemctl, restart, consul ] 
- [ systemctl, restart, nomad ] 
