---

- name: set default python to python3
  become: yes
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    owner: root
    group: root
    state: link

- name: install docker python lib for ansible
  pip:
    name: docker
