---

- name: install docker on clients
  hosts: all 
  become: yes
  roles:
    - docker-install

- name: consul install
  hosts: all
  order: sorted
  become: yes
  roles:
    - consul-install

- name: nomad install
  hosts: all
  order: sorted
  become: yes
  roles:
    - nomad-install

- name: terraform install
  hosts: all
  become: yes
  roles:
    - terraform-install

